import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import useScrollAnimation from "@hooks/useScrollAnimation";

// const [ref, controls] = useScrollAnimation(0.8);
// const onScrollAnimation = {
//   visible: { opacity: 1, transition: { duration: 1 } },
//   hidden: { opacity: 0 },
// };

const Home: NextPage = () => {
  return (
    // <motion.section
    //   ref={ref}
    //   animate={controls}
    //   initial="hidden"
    //   variants={onScrollAnimation}
    //   id="about"
    //   className={classNames(styles.about, "flex-col-center-center")}
    // >
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Time to see my profile</h1>
      </main>

      <footer className={styles.footer}>
        <p> by Joukha</p>
      </footer>
    </div>
    // </motion.section>
  );
};

export default Home;
